<br>
<center>
<table style="width:920">
<tr>
    <td class="trans" width=120px rowspan=8  colspan=1 align=left valign=top>  <img src="../gif/BWCLogo.jpg"          width=90px ><br><br>
     <table>
     <tr> <td width=100px class="trans" valign=top align=left> 
<b>Verein</b>
    </td>
    </tr>
     <tr><td class="trans" align=left valign=middle> 
     &nbsp;  <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/willkommen.shtml">Start!</a>
    </td></tr>
    <tr><td class="trans" align=left valign=middle> 
     &nbsp;  <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/vorstand.shtml">Vorstand</a>
    </td></tr>
    <tr><td class="trans" align=left valign=middle> 
    &nbsp;    <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pdf/satzung.pdf">Satzung </a>

    </td></tr>
    <tr><td class="trans" align=left valign=middle> 
    &nbsp;   <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/mitglied.shtml">Beitreten</a>
    </td></tr>
     <tr><td class="trans" align=left valign=middle> 
    &nbsp;   <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/kontakt.shtml">Kontakt
<br><font color=#880000>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aktuelles</font>
</a>
    </td></tr>
    <tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/paragraph.jpg" width=12px >
    <a href="../pages/impressum.shtml"> Impressum                                 </a>
   </td></tr>


    
    <tr>
    <td width=100px class="trans" align=left> <br>
<b>Sport</b>
    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/training.shtml">Training</a>

    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/matleihe.shtml">Material </a>

    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;    <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/regeln.shtml">Regeln</a>

</td></tr><tr>
    <td width=100px class="trans" align=left> <br>
<b>Saison</b>
    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/blinkendes_23.gif" width=12px >
    <a href="../pages/termine.shtml">Termine </a>

    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="../pages/fahrten.shtml">Fahrten </a>

    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="../gallery/index.shtml">Gallery</a>
 
 </td></tr><tr>
    <td width=100px class="trans" align=left> <br>
<b>links</b>
     </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="http://www.dailydose.de">daily dose </a>

    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="http://www.surf-forum.com">surf forum </a>

    </td></tr><tr><td class="trans" align=left valign=middle> 
    &nbsp;     <img src="../gif/greyarrow.gif" width=12px >
    <a href="http://www.surfshop-charchulla.de">Surfshop<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Charchulla </a>



    </td></tr></table>
    </td>
    <td class="trans"  width=290px colspan=1 align=left  valign=middle> <b><font size=3   > Bremer Windsurfing Club e.V.</b>    </td>
    <td class="trans" width=75px  colspan=1 align=right  valign=middle> 
    <a href="http://www.windfinder.com/forecast/bremen_stadtwaldsee&wf_cmp=7"><img src="../gif/windfinder.jpg" width=32px></a></td>
    <td class="trans" width=90px  colspan=1 align=right  valign=middle> 
    <a href="https://www.google.de/maps/place/Bremer+Windsurfing+Club/@53.1119616,8.8229816,17z/data=!4m2!3m1!1s0x0:0xa1c80d29dadebbbd"><img src="../gif/googlemaps.jpg" width=30px ></a></td>
    <td class="trans" width=90px colspan=1 align=right   valign=middle> 
    <a href="mailto:info@bremerwindsurfing.de"><img src="../gif/email.jpg"          width=50px ></a></td>
    <td class="trans" width=60px colspan=1 align=right valign=middle> 
    <a href="https://www.facebook.com/windsurfenbremen"><img src="../gif/facebook_small.jpg" width=30px ></a></td>
    <td class="trans" width=60px colspan=1 align=right valign=middle> 
    <a href="../pages/impressum.shtml"><img src="../gif/paragraph.jpg" width=23px ></a></td>
    </tr><tr>
    <td class="trans" colspan=6>
    <hr noshade>
    </td>
    </tr><tr>
    <td colspan=6 class="trans"></td>
    </tr><tr>
    <td colspan=6 class="trans" valign=top align=center><img src="../gif/topbildbwc.jpg" width=770px> </td></tr>
<tr><td colspan=6 class="trans" align=left valign=top>
<br>


